### ISSUE TITLE
co-speakerのセッション情報表示

### ISSUE THREAD

**Issue by goofmint** [DevRelMeetupTokyo/japan-2023#49]
second_speakerをidに引っ張ってくればOK。スピーカーページが参考になるはず。

**Comment by suzukin** [comment]
2日モクモクして考えてダメでした、、すみません @nigiiro-taro に。。

session.second_speakerを引っ張って表示させるところまではいったんですが、firstとの出し分けの条件分岐のロジックがどうしても組めませんでした、ブランチ切ってます。

https://github.com/DevRelMeetupTokyo/japan-2023/tree/feature/co-speaker

second_speakerを有効にすると
https://github.com/DevRelMeetupTokyo/japan-2023/blob/feature/co-speaker/_layouts/person.html#L132
![image](https://user-images.githubusercontent.com/5789999/214578317-0e372f52-8b8f-4a86-9996-05dc94a80b8d.png)

first_speakerの情報が出なくなる
https://github.com/DevRelMeetupTokyo/japan-2023/blob/feature/co-speaker/_layouts/person.html#L105
![Screenshot 2023-01-25 at 22 39 00](https://user-images.githubusercontent.com/5789999/214578151-9f2b5a14-d8a9-4775-b19e-0a48ded9203a.png)

**Comment by suzukin** [comment]
#51 にて対応済み
